apiVersion : apps/v1
kind: Deployment
metadata:
  name: vamshikrishnakalletisampleweatherwebcoreapplicatio 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vamshikrishnakalletisampleweatherwebcoreapplicatio
  template:
    metadata:
      labels:
        app: vamshikrishnakalletisampleweatherwebcoreapplicatio 
    spec:
      containers:
        - name: vamshikrishnakalletisampleweatherwebcoreapplicatio 
          image: ganapathiacr.azurecr.io/vamshikrishnakalletisampleweatherwebcoreapplicatio
          ports:
          - containerPort: 80